spring.application.name=FSAD

spring.datasource.url=jdbc:mysql://localhost:3306/fsad_db
spring.datasource.username=root
spring.datasource.password=Kiriti@2007

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect